// ═══════════════════════════════════════════════════════════════════════════════
// � DATABASE — Luôn dùng PostgreSQL (cả local lẫn production)
// ═══════════════════════════════════════════════════════════════════════════════

export {
  query,
  queryOne,
  execute,
  withTransaction,
  pool,
  getAllPrices,
  replacePrices,
  getAllTiers,
  replaceTiers,
  getAllBulkTiers,
  replaceBulkTiers,
  getAllCustomers,
  replaceCustomers,
  getAllServices,
  replaceServices,
  getAllQuotations,
  replaceQuotations,
  getAllReconLogs,
  replaceReconLogs,
  getAllRegistrationServices,
  replaceRegistrationServices,
  getAllRegistrations,
  replaceRegistrations,
  getAllAuditLogs,
  insertAuditLog,
  getConfig,
  setConfig,
  findUserByUsername,
  getAllUsers,
  createUser,
  updateUser,
  deleteUser,
  initDB,
  TABLE_GETTERS,
  TABLE_SETTERS,
} from "./db-postgres.js";
